X-Forwarded-For handling is unsafe
gin-gonic/gin pull request #2474
Opened 2020-08-20 22:00 UTC by sorenh

- With pull requests:
  - Open your pull request against `master`
  - Your pull request should have no more than two commits, if not you should squash them.
  - It should pass all tests in the available continuous integration systems such as TravisCI.
  - You should add/modify tests to cover your proposed code changes.
  - If your pull request contains a new feature, please document it on the README.

2020-10-01 14:17 UTC, rubensayshi commented
looks good, @thinkerou this really should be merged, it's somewhat dangerous with the current implementation.

and scary to realize this has been going wrong for 6yrs, since it was simplied; 
https://github.com/gin-gonic/gin/commit/18880f921583a6916a8267206094f6535a855acc

2020-11-09 07:23 UTC, billyplus commented
If you trust the proxy, the code would be a bit slower to get clientIp than before.

2020-11-09 08:37 UTC, rubensayshi commented
no, anyone can add a `X-Forwarded-For` header to any request and it will be accepted as the clientIp

2020-11-09 09:05 UTC, billyplus commented
If app is not behind proxies, "ForwardedByClientIP" should be set to false, so "X-Forwarded-For" will be ignored.

2020-11-09 09:42 UTC, rubensayshi commented
but when it is behind a proxy it's very important that it will  parse `X-Forwarded-For` based on a trusted proxies list, without that it's vulnerable to IP spoofing and that is a rather serious vulnerability!

I guess `ForwardedByClientIP` could be false by default... or maybe just make `TrustedProxies` `nil` by default and if it is then skip parsing `X-Forwarded-For`?  
I don't think the default `TrustedProxies` should be `[]string{"0.0.0.0/0"},`as this puts us right back at a insecure default and if `ClientIP()` "just works", then users will never even consider looking into how to configure `TrustedProxies` ...

2020-11-09 12:19 UTC, billyplus commented
Gin is suposed to be fast. 
Mostly app behind proxies should be protected by firewall rules rather than gin itself. 
If what you want is truested list, maybe middleware with configuration would fit your need anyway.

2020-11-17 19:00 UTC, sorenh commented
You can't solve this problem with firewalls.

I don't want to spend more time on this. Without this patch, spoofing client IP's is a cakewalk and there's no way way to prevent it.

It's only a matter of time before it blows up in someone's face. Not mine, because if the Gin maintainers really don't think this sort of thing is important, who knows what other security problems are left around because speed is considered more important?

2020-11-18 14:01 UTC, rubensayshi commented
I agree, this is basically a CVE worthy vulnerability...

2020-11-19 14:15 UTC, hadasbloom commented
Hi @sorenh and @rubensayshi,
As part of the Snyk Security team, we contacted the maintainers to urge for their acknowledgement (@sorenh you are CC'd). We see this as a security issue and are willing to assign it a CVE.
Will keep you updated. Thanks for helping us keep open-source safe!

2021-01-11 08:38 UTC, rubensayshi commented
@thinkerou this really should get some priority!

2021-01-11 13:15 UTC, billyplus commented
Maybe you can define a client IP extractor.
#2608

2021-01-11 13:46 UTC, rubensayshi commented
that's not the problem, the problem is that the current implementation for handling X-Forwarded-For is unsafe

2021-01-11 14:00 UTC, cpl commented
@rubensayshi 
> no, anyone can add a `X-Forwarded-For` header to any request and it will be accepted as the clientIp, it's a vulnerability !

> that's not the problem, the problem is that the current implementation for handling X-Forwarded-For is unsafe

I disagree. The issues is not with the current implementation but with the general understanding of the community, for `ClientIP()`. I for one only expose services behind a Firewall and Proxy (or Loadbalancer). The proxy/LB in my case does a hard Set on a custom Header (`X-Foobar-Ip`) and then my services only read that one; An attacker cat set XFF or RealIP to whatever they want. The code before was doing an OK job of parsing the possible "Client IP" headers, people should understand their own setups and come with solutions (such as proper Proxy configuration). Calling this a "vulnerability" is a bit of a stretch.

I find this PR to be a complicated and complex "fix" for something that can be managed and avoided with a simple config and general good "hygine".

2021-01-11 14:05 UTC, billyplus commented
It's unsafe because you put gin serve directly to your clients. We don't do things like this. we will filter the requests, block proxieds and then send request to gin.
Gin is core. 
Go app in many cases is running in docker container behind nginx proxied, which should keep simple and tiny. 
In fact,  if we only trust limited proxies, we usually block other ip from our firewall. We don't use gin to "Block" things. 
Do we need rate limitor, without rate limitor, server is not safe too. 
The question is, "Does gin want to be an ALL-IN-ONE solution?"

2021-01-11 15:02 UTC, rubensayshi commented
you're both making an great argument that gin should either not handle X-Forwarded-For at all, or do it the right way...

2021-01-11 18:05 UTC, sorenh commented
Not doing it at all sounds like a terrible idea to me. If the authors of a framework like Gin can't get this stuff right, expecting application developers to get it right isn't likely to get better results.

2021-01-11 18:07 UTC, sorenh commented
> > that's not the problem, the problem is that the current implementation for handling X-Forwarded-For is unsafe

Indeed.

> It's unsafe because you put gin serve directly to your clients. We don't do things like this. we will filter the requests, block proxieds and then send request to gin.

Good for you. Not everyone does and nowhere in the documentation tells you do to this. Also, your setup is not the correct setup for many, many use cases.

2021-01-11 18:09 UTC, sorenh commented
This is a complete no-brainer. There's a proposed fix that doesn't even change the default, terrible behavior. I thought leaving the defaults as-is would get this merged in a jiffy.

I'd be more than happy to change the defaults to something that's actually secure, but come on, people. Unless you see actual problems with the patch, what possible reason could there be for not merging it? It solves real problems and doesn't change anything for people who don't care.

2021-01-19 19:32 UTC, sorenh commented
@hadasbloom I think a CVE for this issue is perfectly reasonable, whether it gets fixed right now today or not. It's an existing vulnerability. Whether it ever gets fixed is anybody's guess at this point, but anything to alert users of this problem would be good.

2021-01-20 17:14 UTC, hadasbloom commented
@sorenh I agree and hope it will be fixed soon.

This was assigned the cve - CVE-2020-28483.
You will be able to see it soon also on the Snyk website here: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736

2021-01-23 07:08 UTC, ichiro999 commented
@sorenh I agree and hope it will be fixed soon.

2021-01-23 14:53 UTC, appleboy commented
@thinkerou @javierprovecho We need to take a look.

2021-01-24 14:53 UTC, crashdump commented
This was flagged up by our vulnerability management tools, and I agree with the above, this behaviour needs to either be documented clearly or fixed.

Great to see the maintainers jumping in and acknowledging that something needs to be done to fix this security issue. A shame we had to wait 6 month though, especially since someone spent some time to fix this at the time. It will raise question on how serious the team is about security.

2021-02-07 21:29 UTC, manucorporat commented on context.go
> +	for _, trustedProxy := range e.TrustedProxies {
might be worth it to precompute the array of CIDR on `engine.Run()` and save it to: `engine.trustedCIDR` so we don't need to parse the list of trusted proxies every time, the ClientIP() is called

2021-02-07 21:40 UTC, manucorporat commented
Original maintainer here! happy to jump and help to get this merged asap!

2021-02-07 23:54 UTC, javierprovecho commented
After reviewing this PR we had some feedback about implementation to apply. Therefore @manucorporat opened a new DRAFT PR here, keeping the commit history: https://github.com/gin-gonic/gin/pull/2632

2021-02-08 11:00 UTC, javierprovecho requested changes
Do not merge, we’re reviewing this PR.

2021-02-09 14:58 UTC, manucorporat commented
We didn't hijack it, but I offered a different solution, also I forked your PR as a way you ensure you will be a Co-Author. Nothing has been merged yet, both PRs are open!

While I am the original creator of Gin I have been out of the project for years already, just jumped to offer some help :)

2021-02-09 20:30 UTC, sorenh commented
That sounds like textbook hijacking to me. I've been doing this stuff for decades, so idgaf, but this kind of thing drives new contributors away.

I put time and effort into fixing this security issue. Then it gets ignored for 6 months and then, instead of providing constructive feedback, you just create another PR to fix it up. Especially when it's been sitting there for 6 months and then all of a sudden it can't wait another few days for me to address your concerns?

Why even bother trying?

Again, I've grown a lot of thick skin over the years, so I personally don't care, but if you care at all about future contributors, don't do this again.

2021-02-09 20:30 UTC, closed without merging

2021-02-18 16:53 UTC, mbana commented
> @sorenh I agree and hope it will be fixed soon.
> 
> This was assigned the cve - CVE-2020-28483.
> You will be able to see it soon also on the Snyk website here: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMGINGONICGIN-1041736

I'm in the same boat as above.

Any updates on this pull request?

2021-02-19 22:05 UTC, sorenh commented
> Any updates on this pull request? For example, when a new version with a "fix" will be released?

This pull request is for the 6 month old, functional patch that succesfully addresses a CVE, but the maintainers don't want.

#2632 is the one that might have a chance of getting merged someday.

Also: Seriously reconsider if you can use something other than gin. Since this is the attitude towards security problems, I'm out.

2021-03-30 01:53 UTC, sorenisanerd commented
Wow. Just wow.