feat(binding): support custom struct tag
gin-gonic/gin pull request #2720
Opened 2021-05-14 04:00 UTC by mtt0

#2719

2021-06-05 03:04 UTC, daheige approved these changes

2021-06-25 07:17 UTC, appleboy requested changes

2021-06-25 07:17 UTC, appleboy commented on README.md
> +### Bind form-data request with custom struct and custom tag
add a blank line after h3 header

2021-06-29 15:38 UTC, appleboy approved these changes

2021-06-29 16:53 UTC, thinkerou approved these changes
lgtm

2021-06-29 16:53 UTC, merged