fix: check obj type in protobufBinding
gin-gonic/gin pull request #2851
Opened 2021-08-31 13:05 UTC by Tevic

Change-Id: I194f7010835974b489b497c6d1f1b4e47b99864e

- With pull requests:
  - Open your pull request against `master`
  - Your pull request should have no more than two commits, if not you should squash them.
  - It should pass all tests in the available continuous integration systems such as GitHub Actions.
  - You should add/modify tests to cover your proposed code changes.
  - If your pull request contains a new feature, please document it on the README.

2021-08-31 15:26 UTC, appleboy requested changes

2021-08-31 15:26 UTC, appleboy commented on binding/protobuf.go
> +	if err := proto.Unmarshal(body, msg); err != nil {
Add unit testing

2021-09-02 00:31 UTC, appleboy commented
build fail

2021-09-02 14:54 UTC, appleboy approved these changes

2021-09-06 15:21 UTC, daheige approved these changes

2021-09-07 02:10 UTC, thinkerou approved these changes
lgtm

2021-09-07 02:10 UTC, merged