[GIN-001] - Add TOML bining for gi
gin-gonic/gin pull request #3081
Opened 2022-03-15 09:42 UTC by Valentine-Mario

- With pull requests:
  - Open your pull request against `master`
  - Your pull request should have no more than two commits, if not you should squash them.
  - It should pass all tests in the available continuous integration systems such as GitHub Actions.
  - You should add/modify tests to cover your proposed code changes.
  - If your pull request contains a new feature, please document it on the README.

2022-03-15 10:06 UTC, Valentine-Mario commented
@appleboy can you please help review

2022-03-16 04:36 UTC, efectn commented
I think you should use v2 of github.com/pelletier/go-toml. It's more performant

2022-03-16 06:54 UTC, Valentine-Mario commented
> 

The v2 version is still in beta and might still have numerous bugs at the moment

2022-03-16 08:16 UTC, appleboy requested changes

2022-03-16 08:16 UTC, appleboy commented on binding/toml_test.go
> +// Copyright 2019 Gin Core Team. All rights reserved.
2019 -> 2022

2022-03-16 13:45 UTC, efectn commented
> > 
> 
> The v2 version is still in beta and might still have numerous bugs at the moment

Hugo uses v2, also i think it doesn't have critical bugs.
https://github.com/gohugoio/hugo/commit/a3701e09313695d4a0f6fb0eb7844c1a4befc07a

2022-03-17 08:51 UTC, Valentine-Mario commented
> > > 
> > 
> > 
> > The v2 version is still in beta and might still have numerous bugs at the moment
> 
> Hugo uses v2, also i think it doesn't have critical bugs. [gohugoio/hugo@a3701e0](https://github.com/gohugoio/hugo/commit/a3701e09313695d4a0f6fb0eb7844c1a4befc07a)

The TOML parser has been updated to v2. Please review. Thanks

2022-03-17 09:14 UTC, efectn submitted a review, later dismissed
Looks good to me.

2022-03-17 10:43 UTC, thinkerou commented on go.mod
> +	github.com/pelletier/go-toml/v2 v2.0.0-beta.6
need v1 and v2?

2022-03-17 12:24 UTC, efectn requested changes

2022-03-17 12:24 UTC, efectn commented on go.mod
> +	github.com/BurntSushi/toml v1.0.0
What about remove this dep

2022-03-17 12:44 UTC, Valentine-Mario commented on go.mod
> +	github.com/BurntSushi/toml v1.0.0
Sorry about that. Missed it

2022-03-17 15:32 UTC, appleboy submitted a review, later dismissed

2022-03-18 09:14 UTC, Valentine-Mario commented
@appleboy fixed issues with `gofmt`

2022-03-19 13:18 UTC, appleboy approved these changes

2022-03-19 13:19 UTC, appleboy commented
Wait for @thinkerou approval.

2022-03-20 13:16 UTC, thinkerou approved these changes
lgtm, but please wait unit test ok, thanks!

2022-03-21 07:50 UTC, Valentine-Mario commented
Resolved merge conflict and updated toml binding to use the type `any`

2022-03-22 06:40 UTC, Valentine-Mario commented
> @Valentine-Mario sorry, please fix conflicts again, thanks!

Resolved @thinkerou

2022-03-23 08:19 UTC, Valentine-Mario commented
@thinkerou not sure why this test is failing, com planning about the TOML in the context being undefined

2022-04-02 09:26 UTC, efectn commented
> @thinkerou not sure why this test is failing, com planning about the TOML in the context being undefined

Check https://github.com/gin-gonic/gin/blob/master/binding/binding_nomsgpack.go

2022-04-05 04:06 UTC, appleboy approved these changes

2022-05-28 00:08 UTC, thinkerou commented on binding/toml.go
> +package binding
please add copyright info, thanks!

2022-05-28 00:13 UTC, thinkerou commented on go.mod
> +	github.com/pelletier/go-toml/v2 v2.0.0-beta.6
please update `go-toml` which has released version, thanks!

2022-05-28 00:13 UTC, thinkerou commented on render/toml.go
> +package render
please add copyright info, thanks!

2022-05-28 00:34 UTC, merged