Fix #3500 Add escape logic for header
gin-gonic/gin pull request #3503
Opened 2023-02-17 03:55 UTC by t0rchwo0d

Hi, @appleboy, @thinkerou 

Excuse me, I again think about https://github.com/gin-gonic/gin/pull/3500
I'm sorry to bother you.

`.` delimiter & Repeated `/` delimiter was judged to need to be delete and merge,
So, I request PR again.

- [X] Remove characters outside the allowed range (`alphabets`, `numeric`, `-`, `/`)
- [X] Merge Repeated `/` delimiters into one
- [X] Add Test Case

2023-02-18 00:22 UTC, appleboy requested changes

2023-02-18 00:22 UTC, appleboy commented on gin.go
> +		reg := regexp.MustCompile("[^a-zA-Z0-9/-]+")
move to the top for performance issues. only compile once.

2023-02-18 05:42 UTC, appleboy commented on gin.go
> +		reg := regexp.MustCompile("[^a-zA-Z0-9/-]+")
Only initialize once if moving to the top of this file.

```go
var reg = regexp.MustCompile("[^a-zA-Z0-9/-]+")
```

2023-02-19 06:53 UTC, thinkerou approved these changes

2023-02-19 13:25 UTC, appleboy approved these changes

2023-02-19 13:25 UTC, merged

2024-11-25 14:11 UTC, ksw2000 commented
I have some questions in `routes_test.go`. Why the expectation of **Line205** is `//path` but not `/path` 

https://github.com/gin-gonic/gin/blob/e46bd521859fdfc83c508f1d42c92cb7f91e9fcb/routes_test.go#L205-L211

Why the expectation of **Line221** is `https/gin-goniccom/https/gin-goniccom/path` but not `https/gin-goniccom/path` 

https://github.com/gin-gonic/gin/blob/e46bd521859fdfc83c508f1d42c92cb7f91e9fcb/routes_test.go#L221-L223

Additionally, is there any difference if the URL prefix returned by .Location() includes a leading slash or does not include one?