chore: min go version 1.18
gin-gonic/gin pull request #3511
Opened 2023-02-22 12:19 UTC by thinkerou

2023-02-24 03:11 UTC, mstmdev requested changes

2023-02-24 03:11 UTC, mstmdev commented on README.md
> +$ go install github.com/gin-gonic/gin@latest
`go install` will not update the `go.mod` file, suggest keeping using `go get -u`.

2023-02-24 03:29 UTC, thinkerou commented on context_1.18_test.go
> +// +build !go1.19
thank your remind! I will fix it.
https://github.com/gin-gonic/gin/issues/2665

2023-02-25 08:47 UTC, mstmdev commented
Could we delete all the `any.go` files?

2023-02-26 01:46 UTC, thinkerou commented
> Could we delete all the `any.go` files?

yes, done. please review, thanks!

2023-02-27 01:40 UTC, mstmdev commented
![image](https://user-images.githubusercontent.com/5756338/221452447-c11b6882-f8d9-44ca-92d2-18f9d55bbd57.png)

Replace all the` interface{}` with `any`.

2023-02-27 02:35 UTC, thinkerou commented
> ![image](https://user-images.githubusercontent.com/5756338/221452447-c11b6882-f8d9-44ca-92d2-18f9d55bbd57.png)
> 
> Replace all the `interface{}` with `any`.

@mstmdev thanks a lot! done.

2023-02-27 03:21 UTC, mstmdev approved these changes

2023-02-28 11:20 UTC, thinkerou commented
@appleboy please review, thanks!

2023-02-28 13:07 UTC, appleboy approved these changes

2023-03-01 02:03 UTC, merged