feat: ShouldBindBodyWith shortcut and change doc
gin-gonic/gin pull request #3871
Opened 2024-03-06 08:38 UTC by RedCrazyGhost

Based on this #3823 proposal, I code about shortcuts

Ran into an issue like #3862 during testing

2024-03-12 07:18 UTC, RedCrazyGhost commented
I looked it up, and Red Hat says that YAML is a superset of JSON, and all the data can be parsed in JSON format.

I set out to fix the test case.

2024-03-12 07:40 UTC, RedCrazyGhost commented
Hello, please take a look at the PR I submitted and give me some feedback. This PR provides 4 types of shortcuts to ShouldBindBodyWith, which are JSON, YAML, XML, and TOML.

Take a look at this PR, please. @appleboy @thinkerou @manucorporat

2024-03-13 15:23 UTC, appleboy commented
I will take a look.

2024-03-14 06:13 UTC, appleboy commented
@RedCrazyGhost Please help to fix lint error.

2024-03-14 10:37 UTC, RedCrazyGhost commented
> @RedCrazyGhost Please help to fix lint error.

@appleboy  Thanks for your help, I am trying to fix the error in lint, I have committed fix commit.

2024-03-19 08:41 UTC, RedCrazyGhost commented
Hello, can you help me start the approval flow? @flc1125

2024-03-19 08:46 UTC, flc1125 commented
> Hello, can you help me start the approval flow? @flc1125

I'm not a project member and can't help you. Thanks~

2024-03-19 08:52 UTC, RedCrazyGhost commented
> > Hello, can you help me start the approval flow? @flc1125
> 
> I'm not a project member and can't help you. Thanks~

Okay, I see. Sorry to bother you.

2024-03-20 13:31 UTC, RedCrazyGhost commented
@appleboy Hello, please approve the workflow if you have time

2024-03-21 13:12 UTC, appleboy requested changes

2024-03-22 06:14 UTC, RedCrazyGhost commented on context_test.go
> +		if tt.bindingBody != binding.TOML {
I've changed the code style and clarified the binding type.

Take JSON as an example:
```go
if tt.bindingBody == binding.JSON{
	assert.NoError(t, c.ShouldBindBodyWithJSON(&objJSON))
	assert.Equal(t, typeJSON{"FOO"}, objJSON)
}

if tt.bindingBody == binding.XML {
	assert.Error(t, c.ShouldBindBodyWithJSON(&objJSON))
	assert.Equal(t, typeJSON{}, objJSON)
}

if tt.bindingBody == binding.YAML {
	assert.Error(t, c.ShouldBindBodyWithJSON(&objJSON))
	assert.Equal(t, typeJSON{}, objJSON)
}

if tt.bindingBody == binding.TOML {
	assert.Error(t, c.ShouldBindBodyWithJSON(&objJSON))
	assert.Equal(t, typeJSON{}, objJSON)
}
```

2024-03-23 09:05 UTC, RedCrazyGhost commented
Do I need to pay attention to the CodeCov bot detection report? 

Adding new method shortcuts results in a substantial drop in coverage.
@appleboy

2024-03-23 13:25 UTC, RedCrazyGhost commented
This codecov detection result is not the same as the result of go test coverage.

This makes me very confused!

I don't know how to solve this patch coverage? @appleboy 

termial use code:
```shell
$ go test -coverprofile=coverage.out ./...
```
```shell
$ go tool cover -html=coverage.out
```

<img width="840" alt="image" src="https://github.com/gin-gonic/gin/assets/49381700/df6e2b1f-4d6e-4262-ad68-5d5192be6d32">

2024-03-23 14:08 UTC, appleboy approved these changes

2024-03-23 14:09 UTC, merged

2024-03-23 14:09 UTC, appleboy commented
@RedCrazyGhost I've checked the tests myself, so I won't refer to the data from codecov. :) Thanks.

2024-03-23 14:17 UTC, RedCrazyGhost commented
> @RedCrazyGhost I've checked the tests myself, so I won't refer to the data from codecov. :) Thanks.

Thank you for your support throughout.